const $ = (s) => document.querySelector(s);
const state = { mode:'food', category:'all', search:'', vegetarian:false, cart: loadCart(), detail:null, service:'dine-in' };
const cartKey = 'haandi-cart-v1';
function loadCart(){ try{return JSON.parse(localStorage.getItem(cartKey)||'[]')}catch{return[]}}
function saveCart(){localStorage.setItem(cartKey,JSON.stringify(state.cart)); renderCartCount()}
function esc(str=''){return str.replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>el.classList.remove('show'),2200)}
function activeCats(){return state.mode==='food'?FOOD_CATEGORIES:DRINK_GROUPS.map(g=>[g.id,g.name])}
function renderNav(){
  const nav=$('#categoryNav');nav.innerHTML=activeCats().map(([id,name])=>`<button class="category-link ${state.category===id?'selected':''}" data-category="${id}"><span>${state.mode==='food'?'✦':'◌'}</span>${name}<small>${state.mode==='food'?FOOD.filter(x=>x.category===id).length:''}</small></button>`).join('');
}
function image(url){return `<div class="card-image"><img src="${url}" alt="" loading="lazy" onerror="this.style.display='none'" /></div>`}
function renderFood(){
  const q=state.search.toLowerCase(); let list=FOOD.filter(x=>(state.category==='all'||x.category===state.category)&&(!state.vegetarian||x.vegetarian)&&(!q||`${x.name} ${x.description}`.toLowerCase().includes(q)));
  $('#menuGrid').innerHTML=list.map(x=>`<article class="menu-card" data-id="${x.id}"><button class="card-open" type="button" aria-label="View ${esc(x.name)}">${image(x.image)}<div class="card-body"><div class="card-meta"><span class="diet ${x.vegetarian?'veg':'nonveg'}"><i></i>${x.vegetarian?'VEG':'NON-VEG'}</span>${x.spice?`<span class="spice">${esc(x.spice)}</span>`:''}</div><h3>${esc(x.name)}</h3><p>${esc(x.description)}</p><div class="card-bottom"><span class="price">Price to be confirmed</span><span class="add-circle" aria-hidden="true">+</span></div></div></button></article>`).join('');
  $('#resultCount').textContent=`${list.length} ${list.length===1?'item':'items'}`;$('#emptyState').hidden=!!list.length;$('#menuGrid').hidden=!list.length;
}
function renderDrinks(){
  const q=state.search.toLowerCase(); const groups=DRINK_GROUPS.filter(g=>state.category==='all'||g.id===state.category).map(g=>({...g,subcategories:g.subcategories.map(([n,items])=>[n,items]).filter(([n,i])=>!q||(`${n} ${i}`).toLowerCase().includes(q))})).filter(g=>g.subcategories.length);
  $('#menuGrid').innerHTML=groups.map(g=>`<section class="drink-group"><div class="drink-group-head"><span class="group-index">${String(DRINK_GROUPS.indexOf(g)+1).padStart(2,'0')}</span><div><div class="eyebrow">${g.name.toUpperCase()}</div><h3>${g.name}</h3></div><span class="group-note">${g.id==='spirits'?'30 ml per tot':g.id==='cocktails-mocktails'?'Please drink responsibly':'Subject to availability'}</span></div>${g.subcategories.map(([sub,items])=>`<div class="drink-sub"><h4>${esc(sub)}</h4><div class="drink-items">${items.split(' · ').map(item=>`<button class="drink-item" data-drink="${esc(item)}" data-group="${esc(g.name)}" type="button"><span>${esc(item)}</span><b>＋</b></button>`).join('')}</div></div>`).join('')}</section>`).join('');
  $('#resultCount').textContent=`${groups.reduce((n,g)=>n+g.subcategories.reduce((m,[,items])=>m+items.split(' · ').length,0),0)} drinks`;$('#emptyState').hidden=!!groups.length;$('#menuGrid').hidden=!groups.length;
}
function render(){
  renderNav(); const food=state.mode==='food'; $('#resultKicker').textContent=food?'FOOD MENU':'DRINKS MENU';$('#resultTitle').textContent=state.category==='all'?(food?'All food':'All drinks'):(activeCats().find(x=>x[0]===state.category)||['','All'])[1];$('#categoryLabel').textContent=state.category==='all'?(food?'All food':'All drinks'):(activeCats().find(x=>x[0]===state.category)||['','Category'])[1]; $('#vegToggle').hidden=!food; food?renderFood():renderDrinks();
}
function renderCartCount(){$('#cartCount').textContent=state.cart.reduce((n,x)=>n+x.qty,0)}
function add(item, opts={}){const key=`${item.id||item.name}|${opts.spice||''}|${opts.notes||''}`;const existing=state.cart.find(x=>x.key===key);if(existing)existing.qty++;else state.cart.push({key,id:item.id||item.name,name:item.name,description:item.description||'Drink selection',price:null,qty:1,spice:opts.spice||'',notes:opts.notes||'',image:item.image||''});saveCart();toast(`${item.name} added to your order`)}
function openDetail(item){state.detail=item;$('#detailContent').innerHTML=`${image(item.image||foodImage.soups)}<div class="detail-copy"><div class="card-meta"><span class="diet ${item.vegetarian?'veg':'nonveg'}"><i></i>${item.vegetarian?'VEG':'NON-VEG'}</span>${item.spice?`<span class="spice">${esc(item.spice)}</span>`:''}</div><h2 id="detailName">${esc(item.name)}</h2><p>${esc(item.description||'Selected from the Haandi drinks menu.')}</p><p class="detail-note">Your preference is a request for the kitchen and is subject to restaurant confirmation.</p><label class="field-label">Spice preference<select id="spicePref"><option value="">Use menu default${item.spice?` (${esc(item.spice)})`:''}</option><option>Mild</option><option>Medium</option><option>Spicy</option><option>Less spicy</option><option>More spicy</option></select></label><label class="field-label">Special instructions<textarea id="itemNotes" rows="3" placeholder="Less salt, no garnish..." ></textarea></label><div class="detail-actions"><span>Price to be confirmed</span><button class="primary-button" id="detailAdd" type="button">Add to order <span>＋</span></button></div></div>`;showSheet('detail');$('#detailAdd').onclick=()=>{add(item,{spice:$('#spicePref').value,notes:$('#itemNotes').value});closeSheets()}}
function showSheet(which){$('#backdrop').hidden=false;document.body.classList.add('sheet-open');const el=which==='detail'?$('#detailSheet'):$('#orderSheet');el.classList.add('open');el.setAttribute('aria-hidden','false');setTimeout(()=>el.querySelector('button, input, select, textarea')?.focus(),30)}
function closeSheets(){document.body.classList.remove('sheet-open');['detailSheet','orderSheet'].forEach(id=>{$('#'+id).classList.remove('open');$('#'+id).setAttribute('aria-hidden','true')});$('#backdrop').hidden=true}
function renderOrder(){
 const has=state.cart.length; const lines=state.cart.map((x,i)=>`<div class="order-line"><div class="line-thumb">${x.image?`<img src="${x.image}" alt="" />`:''}</div><div class="line-main"><b>${esc(x.name)}</b><small>${x.spice?`Spice: ${esc(x.spice)} · `:''}${x.notes?esc(x.notes):'No special instructions'}</small><div class="qty"><button data-dec="${i}" type="button">−</button><span>${x.qty}</span><button data-inc="${i}" type="button">＋</button><button class="remove" data-remove="${i}" type="button">Remove</button></div></div><span class="line-price">TBC</span></div>`).join('');
 const contactFields=state.service==='dine-in'?'<label>Table number<input name="table" required placeholder="e.g. 14" /></label>':'<label>Phone number<input name="phone" required placeholder="+256 ..." /></label>';
 const extraFields=state.service==='takeaway'?'<label>Preferred pickup time<input name="time" required placeholder="e.g. 19:30" /></label>':state.service==='delivery'?'<label>Address<input name="address" required placeholder="Delivery address" /></label><label>Location link <small>(optional)</small><input name="location" placeholder="Google Maps link" /></label>':'';
 $('#orderContent').innerHTML=has?`<div class="preview-banner"><span>PREVIEW MODE</span><p>Prices are being confirmed by the restaurant. Live WhatsApp checkout is disabled until prices are complete.</p></div><div class="order-lines">${lines}</div><div class="order-total"><span>Subtotal</span><b>Price to be confirmed</b></div><div class="service-tabs"><button class="${state.service==='dine-in'?'active':''}" data-service="dine-in" type="button">Dine-in</button><button class="${state.service==='takeaway'?'active':''}" data-service="takeaway" type="button">Takeaway</button><button class="${state.service==='delivery'?'active':''}" data-service="delivery" type="button">Delivery</button></div><form id="checkoutForm" class="checkout-form"><label>Name<input name="name" required placeholder="Your name" /></label>${contactFields}${extraFields}<button class="primary-button" type="submit">Preview WhatsApp message <span>↗</span></button></form><div class="order-footnote">Delivery availability and charges will be confirmed by the restaurant.<br />Payment is arranged directly with the restaurant.</div>`:`<div class="empty-order"><div>✦</div><h3>Your order is waiting</h3><p>Add a dish or drink to begin.</p><button class="primary-button" data-close="order" type="button">Explore menu</button></div>`;
 $('#orderContent').querySelectorAll('[data-inc]').forEach(b=>b.onclick=()=>{state.cart[b.dataset.inc].qty++;saveCart();renderOrder()});$('#orderContent').querySelectorAll('[data-dec]').forEach(b=>b.onclick=()=>{const x=state.cart[b.dataset.dec];x.qty--;if(x.qty<1)state.cart.splice(b.dataset.dec,1);saveCart();renderOrder()});$('#orderContent').querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{state.cart.splice(b.dataset.remove,1);saveCart();renderOrder()});$('#orderContent').querySelectorAll('[data-service]').forEach(b=>b.onclick=()=>{state.service=b.dataset.service;renderOrder()});$('#checkoutForm')?.addEventListener('submit', e=>{e.preventDefault();showMessagePreview(new FormData(e.target))});
}
function showMessagePreview(form){const d=Object.fromEntries(form.entries());const itemText=state.cart.map(x=>`${x.qty} × ${x.name}${x.spice?` [${x.spice}]`:''}${x.notes?` — ${x.notes}`:''}`).join('\n');const customer=state.service==='dine-in'?`Name: ${d.name}\nTable: ${d.table}`:`Name: ${d.name}\nPhone: ${d.phone}\n${state.service==='takeaway'?`Pickup time: ${d.time}`:`Address: ${d.address}\nLocation: ${d.location||'Not provided'}`}`;const msg=`HAANDI RESTAURANT ORDER\nBranch: ${$('#branchSelect').value}\nService: ${state.service}\n\n${customer}\n\nItems:\n${itemText}\n\nSubtotal: Price to be confirmed\nDelivery charges: Awaiting confirmation\nPayment: Arranged directly with the restaurant.\n\nPlease confirm acceptance of this order.`;$('#orderContent').innerHTML=`<div class="message-preview"><div class="preview-label">MESSAGE PREVIEW</div><pre id="messageText">${esc(msg)}</pre><div class="preview-actions"><button class="secondary-button" id="copyMessage" type="button">Copy order</button><button class="primary-button" id="whatsApp" type="button" disabled>Continue to WhatsApp <span>↗</span></button></div><p class="handoff-note">Live checkout stays disabled until all prices are populated. When enabled, WhatsApp will open with this message; you must send it, and Haandi must confirm acceptance.</p></div>`;$('#copyMessage').onclick=()=>navigator.clipboard?.writeText(msg).then(()=>toast('Order copied to clipboard')).catch(()=>toast('Select and copy the message'));}
 document.addEventListener('click',e=>{const cat=e.target.closest('[data-category]');if(cat){state.category=cat.dataset.category;render()}const card=e.target.closest('.menu-card');if(card){const item=FOOD.find(x=>x.id===card.dataset.id);if(item)openDetail(item)}const drink=e.target.closest('[data-drink]');if(drink)openDetail({name:drink.dataset.drink,description:`${drink.dataset.group} selection. Serving and availability guidance applies.`,image:foodImage.soups});if(e.target.matches('[data-close]'))closeSheets()});
 $('#searchInput').oninput=e=>{state.search=e.target.value;render()};$('#vegToggle').onclick=()=>{state.vegetarian=!state.vegetarian;$('#vegToggle').classList.toggle('active',state.vegetarian);$('#vegToggle').setAttribute('aria-pressed',state.vegetarian);render()};$('#categoryTrigger').onclick=()=>document.querySelector('.category-sidebar').classList.toggle('mobile-open');$('#openCart').onclick=()=>{renderOrder();showSheet('order')};$('#backdrop').onclick=closeSheets;document.addEventListener('keydown',e=>{if(e.key==='Escape')closeSheets()});document.querySelectorAll('.mode').forEach(b=>b.onclick=()=>{state.mode=b.dataset.mode;state.category='all';state.search='';$('#searchInput').value='';document.querySelectorAll('.mode').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-selected',x===b)});render()});renderCartCount();render();
