const CONFIG = { whatsapp: '256749710372', website: 'https://haandirestaurantkampala.com/', liveOrdering: false, branches: ['kampala-road', 'naguru'] };
const FOOD_CATEGORIES = [
  ['soups','Soups'],['salads','Salads'],['veg-starters','Vegetarian Starters'],['chicken-starters','Chicken Starters'],['fish-starters','Fish & Prawn Starters'],['mutton-starters','Mutton & Lamb Starters'],['chicken-mains','Chicken Main Course'],['fish-mains','Fish Main Course'],['mutton-mains','Mutton & Lamb Main Course'],['rice','Rice & Biryani'],['sides','Chips, Papad & Sides']
];
const F = (category, name, description, spice, vegetarian=false) => ({ id: name.toLowerCase().replace(/[^a-z0-9]+/g,'-'), category, name, description, spice: spice || null, vegetarian, price: null, image: null });
const FOOD_CATEGORY_IMAGES = {soups:'images/categories/Food/soups.webp',salads:'images/categories/Food/salads.webp','veg-starters':'images/categories/Food/vegetarian-starters.webp','chicken-starters':'images/categories/Food/chicken-starters.webp','fish-starters':'images/categories/Food/fish-prawn-starters.webp','mutton-starters':'images/categories/Food/mutton-lamb-starters.webp','chicken-mains':'images/categories/Food/chicken-main-course.webp','fish-mains':'images/categories/Food/fish-main-course.webp','mutton-mains':'images/categories/Food/mutton-lamb-main-course.webp',rice:'images/categories/Food/rice-biryani.webp',sides:'images/categories/Food/chips-papad-sides.webp'};
const FOOD = [
...['Cream of Tomato Soup|smooth, creamy tomato soup with a light tangy flavour.|Mild|v','Hot & Sour Soup|vegetables in a flavourful sour and spicy broth.|Medium|v','Chicken Manchow Soup|chicken and vegetables in a garlicky soup with chilli and herbs.|Medium–Spicy','Chicken Sweet Corn Soup|light chicken soup with sweet corn and egg.|Mild','Chicken Hot & Sour Soup|chicken and vegetables in a tangy, spicy broth.|Medium','Vegetable Noodle Soup|light vegetable broth with noodles and fresh vegetables.|Mild|v','Vegetable Sweet Corn Soup|light vegetable soup with sweet corn.|Mild|v'].map(x=>{let [n,d,s,v]=x.split('|');return F('soups',n,d,s,v==='v')}),
...['Green Salad|cucumber, tomato, onion, lettuce and seasonal vegetables.|Mild|v','Green Chutney|fresh coriander, mint and green chilli chutney.|Medium–Spicy|v','Golden City Quinoa Salad|quinoa with fresh vegetables and a light dressing.|Mild|v','Kachumbari Salad|fresh tomato, onion, coriander and lemon.|Mild|v'].map(x=>{let [n,d,s,v]=x.split('|');return F('salads',n,d,s,v==='v')}),
...['Paneer Tikka|marinated cottage cheese grilled in the tandoor.|Medium','Haandi Style Paneer Tikka|grilled paneer with Haandi’s special marinade.|Medium','Paneer Malai Tikka|soft paneer marinated with cream and mild spices.|Mild','Paneer Achari Tikka|paneer with tangy Indian pickle spices.|Medium','Tandoori Paneer Tikka|paneer marinated in yoghurt and tandoori spices, grilled.|Medium','Chilli Paneer|crispy paneer with chilli, onion and capsicum.|Medium–Spicy','Paneer Salt & Pepper|crispy paneer with black pepper and seasoning.|Medium','Paneer Manchurian|crispy paneer in a sweet, tangy, spicy Indo-Chinese sauce.|Medium','Chinese-Style Paneer|paneer stir-fried with vegetables and Chinese-style sauce.|Medium','Broccoli & Paneer|broccoli and paneer with light seasoning.|Mild','Chilli Broccoli|crispy broccoli with chilli, onion and capsicum.|Medium–Spicy','Vegetable Manchurian (Dry)|crispy vegetable balls tossed in Manchurian sauce.|Medium','Vegetable Manchurian (Gravy)|vegetable balls in flavourful Manchurian gravy.|Medium','Chilli Soya Chaap|soya chaap with chilli, onion and capsicum.|Medium–Spicy','Crispy Fried Chilli Corn|crispy sweet corn with chilli and seasoning.|Medium','Chilli Mushroom|mushroom with chilli, onion and capsicum.|Medium','Mushroom Salt & Pepper|crispy mushroom with black pepper and seasoning.|Medium','Vegetable Platter|a selection of popular vegetarian starters.|Mild–Medium','Butter Garlic Mushroom|mushroom cooked with butter and fresh garlic.|Mild','Tandoori Mushroom|marinated mushrooms grilled in the tandoor.|Medium'].map(x=>{let [n,d,s]=x.split('|');return F('veg-starters',n,d,s,true)}),
...['Chicken Tikka|chicken marinated in yoghurt and spices, grilled in the tandoor.|Medium','Chicken Reshmi Kebab|soft, juicy kebab with a creamy, mild flavour.|Mild','Chicken Malai Tikka|tender chicken with cream, cheese and mild spices.|Mild','Chicken Achari Tikka|chicken with tangy Indian pickle spices.|Medium','Chicken Angara|smoky grilled chicken with bold spices.|Spicy','Chicken Manchurian|crispy chicken in a sweet, tangy, spicy sauce.|Medium','Chicken Salt & Pepper|crispy chicken with black pepper and seasoning.|Medium','Chilli Chicken|crispy chicken with chilli, onion and capsicum.|Medium–Spicy','Chinese-Style Chicken|stir-fried chicken with vegetables and Chinese-style sauce.|Medium','Chicken Wings|marinated wings, fried or grilled.|Mild–Medium','Chicken Lollipop|wings in lollipop style, crispy and flavourful.|Medium','Chicken 65|crispy fried chicken, aromatic, spicy and slightly tangy.|Spicy','Chicken Drumsticks|marinated drumsticks, grilled or fried until tender.|Mild–Medium'].map(x=>{let [n,d,s]=x.split('|');return F('chicken-starters',n,d,s)}),
...['Crispy Fried Fish|crispy outside, tender inside.|Mild','Fish Tikka|marinated fish grilled with tandoori spices.|Medium','Chilli Fish (Dry)|crispy fish with chilli, onion and capsicum.|Medium–Spicy','Fish Salt & Pepper|crispy fish with black pepper and seasoning.|Medium','Amritsari Fish Fry|crispy fish coated in seasoned gram flour.|Medium','Tandoori Prawns|prawns marinated in yoghurt and tandoori spices, grilled.|Medium','Deep-Fried Prawns|crispy fried prawns with light seasoning.|Mild','Chilli Prawns|prawns with chilli, onion and capsicum.|Medium–Spicy'].map(x=>{let [n,d,s]=x.split('|');return F('fish-starters',n,d,s)}),
...['Mutton Seekh Kebab|minced mutton with herbs and spices, grilled on skewers.|Medium','Mutton Tikka|tender marinated mutton grilled with aromatic spices.|Medium','Mutton Shashlik|grilled mutton with onion and capsicum.|Medium','Mutton Chops|marinated chops grilled until tender and juicy.|Medium','Mutton Pepper Fry|mutton cooked dry with black pepper and spices.|Medium–Spicy','Lamb Chops|tender lamb chops grilled with light seasoning.|Mild–Medium','Lamb Seekh Kebab|minced lamb with herbs and spices, grilled on skewers.|Medium','Chilli Lamb Kebab|lamb cooked with chilli, onion and capsicum.|Medium–Spicy'].map(x=>{let [n,d,s]=x.split('|');return F('mutton-starters',n,d,s)}),
...['Chicken Tikka Masala|tandoori chicken in rich tomato and onion gravy.|Medium','Chicken Curry|traditional curry with onion, tomato and aromatic spices.|Medium','Chicken Handi|tender chicken in rich handi-style gravy.|Medium','Punjabi Chicken|rich Punjabi-style onion and tomato gravy.|Medium','Chicken Korma|creamy, mildly spiced sauce.|Mild','Chicken Coconut Curry|creamy coconut gravy with gentle spices.|Mild–Medium','Chicken Palak|chicken with spinach, garlic and Indian spices.|Medium','Chicken Methi|chicken with fragrant fenugreek leaves and spices.|Medium','Chicken Malabar Curry|chicken with coconut and South Indian spices.|Medium','Chicken Malai Korma|smooth, creamy and mild gravy.|Mild','Chicken Makhani|smooth tomato and butter gravy.|Mild','Butter Chicken|tender chicken in a creamy, buttery tomato sauce.|Mild','Tandoori Chicken Masala|tandoori chicken finished in rich Indian gravy.|Medium'].map(x=>{let [n,d,s]=x.split('|');return F('chicken-mains',n,d,s)}),
...['Fish Curry|traditional onion, tomato and spice gravy.|Medium','Coconut Fish Curry|creamy coconut gravy with gentle spices.|Mild–Medium','Fish Makhani|creamy tomato and butter gravy.|Mild','Fish Malabar Curry|coconut, curry leaves and South Indian spices.|Medium'].map(x=>{let [n,d,s]=x.split('|');return F('fish-mains',n,d,s)}),
...['Mutton Rogan Josh|slow-cooked in rich, aromatic Kashmiri-style gravy.|Medium','Mutton Masala|rich onion, tomato and spice gravy.|Medium','Mutton Bhuna|slow-cooked with thick, concentrated masala.|Medium','Mutton Vindaloo|vinegar, spices and chilli for a hot, tangy flavour.|Spicy–Very Spicy','Mutton Korma|rich, creamy and mild gravy.|Mild','Mutton Pepper Fry (Dry)|cooked dry with black pepper and spices.|Spicy','Mutton Seekh Masala|seekh kebab in rich masala gravy.|Medium','Mutton Handi|slow-cooked in rich handi-style gravy.|Medium','Mutton Keema|minced mutton with onion, tomato and spices.|Medium','Lamb Shank Masala|slow-cooked lamb shank in rich masala gravy.|Medium'].map(x=>{let [n,d,s]=x.split('|');return F('mutton-mains',n,d,s)}),
...['Steamed Rice|plain, fluffy basmati rice.|Mild|v','Special Rice|fragrant rice with vegetables and light seasoning.|Mild|v','Vegetable Pulao|basmati with vegetables and aromatic spices.|Mild|v','Onion Pulao|fragrant rice with fried onions and aromatic spices.|Mild|v','Vegetable Biryani|basmati layered with vegetables, herbs and biryani spices.|Medium|v','Chicken Biryani|basmati layered with chicken, herbs and biryani spices.|Medium','Mutton Biryani|basmati layered with tender mutton and spices.|Medium','Hyderabadi Chicken Biryani|rich, aromatic biryani with stronger spices.|Medium–Spicy','Chicken Jalfrezi Rice|rice with chicken, vegetables and spicy seasoning.|Medium–Spicy'].map(x=>{let [n,d,s,v]=x.split('|');return F('rice',n,d,s,v==='v')}),
...['Plain Chips|freshly fried, crispy and lightly salted.||v','Masala Chips|crispy chips tossed with aromatic masala.|Medium|v','Plain Papad (Roasted)|thin, crispy roasted papad with light seasoning.||v','Masala Papad (Roasted)|topped with onion, tomato, coriander and spices.|Medium|v','Crispy Fried Garlic Chips (Spicy)|crispy chips with fried garlic and chilli.|Spicy|v','Crispy Fried Garlic Chips (Mild)|crispy garlic chips with light seasoning.|Mild|v','Paneer Pakora|paneer in seasoned gram flour, fried until crispy.|Mild–Medium|v','Masala Bhajiya|crispy vegetable fritters with gram flour and Indian spices.|Medium|v','Crispy Fried Onion Rings|light batter, golden and crispy.||v','Honey Chilli Potato|crispy potato in a sweet, tangy, spicy honey-chilli sauce.|Medium–Spicy|v'].map(x=>{let [n,d,s,v]=x.split('|');return F('sides',n,d,s,v==='v')})
];
const DRINK_GROUPS = [
  {
    "id": "refreshments",
    "name": "Refreshments",
    "image": "images/categories/Drinks/refreshments.webp"
  },
  {
    "id": "cocktails-mocktails",
    "name": "Cocktails & Mocktails",
    "image": "images/categories/Drinks/cocktails-mocktails.webp"
  },
  {
    "id": "beer",
    "name": "Beer",
    "image": "images/categories/Drinks/beer.webp"
  },
  {
    "id": "wine",
    "name": "Wine",
    "image": "images/categories/Drinks/wine.webp"
  },
  {
    "id": "spirits",
    "name": "Spirits",
    "image": "images/categories/Drinks/spirits.webp"
  },
  {
    "id": "mixers",
    "name": "Mixers & Garnishes",
    "image": "images/categories/Drinks/mixers-garnishes.webp"
  }
];
const DRINKS = [
  {
    "id": "refreshments-water-soft-beverages-still-water-500-ml",
    "name": "Still Water (500 ml)",
    "category": "refreshments",
    "subcategory": "Water & Soft Beverages",
    "description": "Freshly squeezed lime, your choice of sweet, salted or mixed.",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": "500 ml"
  },
  {
    "id": "refreshments-water-soft-beverages-sparkling-water",
    "name": "Sparkling Water",
    "category": "refreshments",
    "subcategory": "Water & Soft Beverages",
    "description": "Freshly squeezed lime, your choice of sweet, salted or mixed.",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "refreshments-water-soft-beverages-soda-water",
    "name": "Soda Water",
    "category": "refreshments",
    "subcategory": "Water & Soft Beverages",
    "description": "Freshly squeezed lime, your choice of sweet, salted or mixed.",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "refreshments-water-soft-beverages-assorted-soft-drinks",
    "name": "Assorted Soft Drinks",
    "category": "refreshments",
    "subcategory": "Water & Soft Beverages",
    "description": "Freshly squeezed lime, your choice of sweet, salted or mixed.",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "refreshments-water-soft-beverages-coke-zero",
    "name": "Coke Zero",
    "category": "refreshments",
    "subcategory": "Water & Soft Beverages",
    "description": "Freshly squeezed lime, your choice of sweet, salted or mixed.",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "refreshments-water-soft-beverages-fresh-lime-soda-sweet-salted-mixed",
    "name": "Fresh Lime Soda (Sweet / Salted / Mixed)",
    "category": "refreshments",
    "subcategory": "Water & Soft Beverages",
    "description": "Freshly squeezed lime, your choice of sweet, salted or mixed.",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": "Sweet / Salted / Mixed"
  },
  {
    "id": "refreshments-water-soft-beverages-fresh-lime-juice-plain-mixed",
    "name": "Fresh Lime Juice (Plain / Mixed)",
    "category": "refreshments",
    "subcategory": "Water & Soft Beverages",
    "description": "Freshly squeezed lime, your choice of sweet, salted or mixed.",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": "Plain / Mixed"
  },
  {
    "id": "refreshments-fresh-juices-mixed-fresh-juice",
    "name": "Mixed Fresh Juice",
    "category": "refreshments",
    "subcategory": "Fresh Juices",
    "description": "Made with selected seasonal fruits.",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "refreshments-fresh-juices-passion-fruit-juice",
    "name": "Passion Fruit Juice",
    "category": "refreshments",
    "subcategory": "Fresh Juices",
    "description": "Made with selected seasonal fruits.",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "refreshments-fresh-juices-mango-juice",
    "name": "Mango Juice",
    "category": "refreshments",
    "subcategory": "Fresh Juices",
    "description": "Made with selected seasonal fruits.",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "refreshments-fresh-juices-fresh-orange-juice",
    "name": "Fresh Orange Juice",
    "category": "refreshments",
    "subcategory": "Fresh Juices",
    "description": "Made with selected seasonal fruits.",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "refreshments-fresh-juices-watermelon-juice",
    "name": "Watermelon Juice",
    "category": "refreshments",
    "subcategory": "Fresh Juices",
    "description": "Made with selected seasonal fruits.",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "refreshments-fresh-juices-fresh-pineapple-juice",
    "name": "Fresh Pineapple Juice",
    "category": "refreshments",
    "subcategory": "Fresh Juices",
    "description": "Made with selected seasonal fruits.",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "refreshments-fresh-juices-mint-pineapple-juice",
    "name": "Mint Pineapple Juice",
    "category": "refreshments",
    "subcategory": "Fresh Juices",
    "description": "Made with selected seasonal fruits.",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "refreshments-smoothies-mango-strawberry",
    "name": "Mango & Strawberry",
    "category": "refreshments",
    "subcategory": "Smoothies",
    "description": "Fresh fruits blended smooth, creamy and refreshing.",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "refreshments-smoothies-strawberry-banana",
    "name": "Strawberry & Banana",
    "category": "refreshments",
    "subcategory": "Smoothies",
    "description": "Fresh fruits blended smooth, creamy and refreshing.",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "refreshments-smoothies-mango-banana",
    "name": "Mango & Banana",
    "category": "refreshments",
    "subcategory": "Smoothies",
    "description": "Fresh fruits blended smooth, creamy and refreshing.",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "refreshments-smoothies-tropical-fruit",
    "name": "Tropical Fruit",
    "category": "refreshments",
    "subcategory": "Smoothies",
    "description": "Fresh fruits blended smooth, creamy and refreshing.",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "refreshments-smoothies-avocado",
    "name": "Avocado",
    "category": "refreshments",
    "subcategory": "Smoothies",
    "description": "Fresh fruits blended smooth, creamy and refreshing.",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "refreshments-smoothies-mango-pineapple-lemon-mint",
    "name": "Mango, Pineapple, Lemon & Mint",
    "category": "refreshments",
    "subcategory": "Smoothies",
    "description": "Fresh fruits blended smooth, creamy and refreshing.",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "refreshments-smoothies-green-healthy",
    "name": "Green Healthy",
    "category": "refreshments",
    "subcategory": "Smoothies",
    "description": "Fresh fruits blended smooth, creamy and refreshing.",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "refreshments-lassi-indian-refreshments-mango-lassi",
    "name": "Mango Lassi",
    "category": "refreshments",
    "subcategory": "Lassi & Indian Refreshments",
    "description": "creamy yoghurt blended with ripe mango.",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "refreshments-lassi-indian-refreshments-sweet-lassi",
    "name": "Sweet Lassi",
    "category": "refreshments",
    "subcategory": "Lassi & Indian Refreshments",
    "description": "smooth chilled yoghurt, gently sweet.",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "refreshments-lassi-indian-refreshments-salted-lassi",
    "name": "Salted Lassi",
    "category": "refreshments",
    "subcategory": "Lassi & Indian Refreshments",
    "description": "yoghurt with a delicate touch of salt and traditional seasoning.",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "refreshments-lassi-indian-refreshments-chaas-buttermilk",
    "name": "Chaas / Buttermilk",
    "category": "refreshments",
    "subcategory": "Lassi & Indian Refreshments",
    "description": "light, spiced buttermilk, traditionally enjoyed with Indian cuisine.",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "refreshments-fresh-lemonade-classic-fresh-lemonade",
    "name": "Classic Fresh Lemonade",
    "category": "refreshments",
    "subcategory": "Fresh Lemonade",
    "description": "fresh lemon balanced with sweetness, served chilled.",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "refreshments-fresh-lemonade-mint-lemonade",
    "name": "Mint Lemonade",
    "category": "refreshments",
    "subcategory": "Fresh Lemonade",
    "description": "fresh lemon and cooling mint.",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "refreshments-fresh-lemonade-strawberry-lemonade",
    "name": "Strawberry Lemonade",
    "category": "refreshments",
    "subcategory": "Fresh Lemonade",
    "description": "fresh strawberries and lemon, sweet and tangy.",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "refreshments-fresh-lemonade-passion-fruit-lemonade",
    "name": "Passion Fruit Lemonade",
    "category": "refreshments",
    "subcategory": "Fresh Lemonade",
    "description": "passion fruit and fresh lemon, bright and tropical.",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "refreshments-fresh-lemonade-sparkling-lemonade",
    "name": "Sparkling Lemonade",
    "category": "refreshments",
    "subcategory": "Fresh Lemonade",
    "description": "fresh lemon and sparkling water, lively and crisp.",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "refreshments-tea-masala-tea",
    "name": "Masala Tea",
    "category": "refreshments",
    "subcategory": "Tea",
    "description": "black tea with aromatic Indian spices and milk.",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "refreshments-tea-african-tea",
    "name": "African Tea",
    "category": "refreshments",
    "subcategory": "Tea",
    "description": "comforting, smooth and aromatic, African style.",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "refreshments-tea-lemon-tea",
    "name": "Lemon Tea",
    "category": "refreshments",
    "subcategory": "Tea",
    "description": "light tea with fresh lemon.",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "refreshments-tea-black-tea",
    "name": "Black Tea",
    "category": "refreshments",
    "subcategory": "Tea",
    "description": "classic brewed black tea.",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "refreshments-tea-ginger-lemon-tea",
    "name": "Ginger Lemon Tea",
    "category": "refreshments",
    "subcategory": "Tea",
    "description": "fresh ginger and lemon in hot tea.",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "refreshments-tea-dawa-tea",
    "name": "Dawa Tea",
    "category": "refreshments",
    "subcategory": "Tea",
    "description": "warming blend of lemon, ginger and honey.",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "refreshments-tea-green-tea",
    "name": "Green Tea",
    "category": "refreshments",
    "subcategory": "Tea",
    "description": "delicate, clean and light.",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "refreshments-iced-tea-lemon-iced-tea",
    "name": "Lemon Iced Tea",
    "category": "refreshments",
    "subcategory": "Iced Tea",
    "description": "black tea with fresh lemon, ice-cold.",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "refreshments-iced-tea-ginger-lemon-iced-tea",
    "name": "Ginger Lemon Iced Tea",
    "category": "refreshments",
    "subcategory": "Iced Tea",
    "description": "ginger and lemon, zesty finish.",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "refreshments-iced-tea-strawberry-iced-tea",
    "name": "Strawberry Iced Tea",
    "category": "refreshments",
    "subcategory": "Iced Tea",
    "description": "sweet strawberry, fruity finish.",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "refreshments-iced-tea-peach-iced-tea",
    "name": "Peach Iced Tea",
    "category": "refreshments",
    "subcategory": "Iced Tea",
    "description": "delicate peach, smooth and fruity.",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "refreshments-iced-tea-passion-fruit-iced-tea",
    "name": "Passion Fruit Iced Tea",
    "category": "refreshments",
    "subcategory": "Iced Tea",
    "description": "fresh passion fruit, vibrant and tropical.",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "refreshments-coffee-african-coffee",
    "name": "African Coffee",
    "category": "refreshments",
    "subcategory": "Coffee",
    "description": "",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "refreshments-coffee-black-coffee",
    "name": "Black Coffee",
    "category": "refreshments",
    "subcategory": "Coffee",
    "description": "",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "refreshments-coffee-espresso",
    "name": "Espresso",
    "category": "refreshments",
    "subcategory": "Coffee",
    "description": "rich, concentrated, smooth",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "refreshments-coffee-double-espresso",
    "name": "Double Espresso",
    "category": "refreshments",
    "subcategory": "Coffee",
    "description": "",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "refreshments-coffee-americano",
    "name": "Americano",
    "category": "refreshments",
    "subcategory": "Coffee",
    "description": "",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "refreshments-coffee-cappuccino",
    "name": "Cappuccino",
    "category": "refreshments",
    "subcategory": "Coffee",
    "description": "espresso, steamed milk, delicate foam",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "refreshments-coffee-caf-latte",
    "name": "Café Latte",
    "category": "refreshments",
    "subcategory": "Coffee",
    "description": "espresso, steamed milk, light foam",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "refreshments-coffee-caf-mocha",
    "name": "Café Mocha",
    "category": "refreshments",
    "subcategory": "Coffee",
    "description": "espresso, chocolate, steamed milk",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "refreshments-coffee-cold-coffee",
    "name": "Cold Coffee",
    "category": "refreshments",
    "subcategory": "Coffee",
    "description": "smooth, chilled",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "refreshments-coffee-iced-coffee",
    "name": "Iced Coffee",
    "category": "refreshments",
    "subcategory": "Coffee",
    "description": "espresso and chilled coffee over ice",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "refreshments-milkshakes-vanilla",
    "name": "Vanilla",
    "category": "refreshments",
    "subcategory": "Milkshakes",
    "description": "Thick, creamy and freshly blended.",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "refreshments-milkshakes-mango",
    "name": "Mango",
    "category": "refreshments",
    "subcategory": "Milkshakes",
    "description": "Thick, creamy and freshly blended.",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "refreshments-milkshakes-chocolate",
    "name": "Chocolate",
    "category": "refreshments",
    "subcategory": "Milkshakes",
    "description": "Thick, creamy and freshly blended.",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "refreshments-milkshakes-strawberry",
    "name": "Strawberry",
    "category": "refreshments",
    "subcategory": "Milkshakes",
    "description": "Thick, creamy and freshly blended.",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "refreshments-milkshakes-papaya",
    "name": "Papaya Milkshake",
    "category": "refreshments",
    "subcategory": "Milkshakes",
    "description": "Thick, creamy and freshly blended.",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "refreshments-milkshakes-caramel",
    "name": "Caramel",
    "category": "refreshments",
    "subcategory": "Milkshakes",
    "description": "Thick, creamy and freshly blended.",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "refreshments-milkshakes-peanut-butter",
    "name": "Peanut Butter",
    "category": "refreshments",
    "subcategory": "Milkshakes",
    "description": "Thick, creamy and freshly blended.",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "refreshments-milkshakes-oreo",
    "name": "Oreo",
    "category": "refreshments",
    "subcategory": "Milkshakes",
    "description": "creamy vanilla with crushed Oreo cookies.",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "refreshments-milkshakes-kitkat",
    "name": "KitKat",
    "category": "refreshments",
    "subcategory": "Milkshakes",
    "description": "creamy, with chocolate-wafer flavour.",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "refreshments-milkshakes-lotus-biscoff",
    "name": "Lotus Biscoff",
    "category": "refreshments",
    "subcategory": "Milkshakes",
    "description": "creamy vanilla with caramelised biscuit flavour.",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "refreshments-milkshakes-assorted-fruit",
    "name": "Assorted Fruit",
    "category": "refreshments",
    "subcategory": "Milkshakes",
    "description": "a blend of selected fresh fruits.",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "cocktails-mocktails-virgin-mojito-collection-classic-virgin-mojito",
    "name": "Classic Virgin Mojito",
    "category": "cocktails-mocktails",
    "subcategory": "Virgin Mojito Collection",
    "description": "fresh lime, mint, sugar and soda.",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "cocktails-mocktails-virgin-mojito-collection-passion-fruit-virgin-mojito",
    "name": "Passion Fruit Virgin Mojito",
    "category": "cocktails-mocktails",
    "subcategory": "Virgin Mojito Collection",
    "description": "passion fruit, lime, mint and soda, tangy finish.",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "cocktails-mocktails-virgin-mojito-collection-strawberry-virgin-mojito",
    "name": "Strawberry Virgin Mojito",
    "category": "cocktails-mocktails",
    "subcategory": "Virgin Mojito Collection",
    "description": "fresh strawberries, lime, mint and soda.",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "cocktails-mocktails-virgin-mojito-collection-mango-virgin-mojito",
    "name": "Mango Virgin Mojito",
    "category": "cocktails-mocktails",
    "subcategory": "Virgin Mojito Collection",
    "description": "ripe mango, lime, mint and soda.",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "cocktails-mocktails-signature-mocktails-shirley-temple",
    "name": "Shirley Temple",
    "category": "cocktails-mocktails",
    "subcategory": "Signature Mocktails",
    "description": "sparkling citrus with grenadine.",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "cocktails-mocktails-signature-mocktails-fruit-punch",
    "name": "Fruit Punch",
    "category": "cocktails-mocktails",
    "subcategory": "Signature Mocktails",
    "description": "tropical fruit juices, sweet and tangy.",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "cocktails-mocktails-signature-mocktails-virgin-pi-a-colada",
    "name": "Virgin Piña Colada",
    "category": "cocktails-mocktails",
    "subcategory": "Signature Mocktails",
    "description": "creamy coconut and pineapple.",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "cocktails-mocktails-signature-mocktails-virgin-pi-a-colada-whole-pineapple",
    "name": "Virgin Piña Colada (Whole Pineapple)",
    "category": "cocktails-mocktails",
    "subcategory": "Signature Mocktails",
    "description": "served inside a whole fresh pineapple.",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": "Whole Pineapple"
  },
  {
    "id": "cocktails-mocktails-signature-mocktails-blue-lagoon",
    "name": "Blue Lagoon",
    "category": "cocktails-mocktails",
    "subcategory": "Signature Mocktails",
    "description": "vodka, citrus and blue curaçao.",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "cocktails-mocktails-signature-mocktails-blue-sea",
    "name": "Blue Sea",
    "category": "cocktails-mocktails",
    "subcategory": "Signature Mocktails",
    "description": "tropical citrus and fruit, finished in blue.",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "cocktails-mocktails-signature-mocktails-kiwi-cooler",
    "name": "Kiwi Cooler",
    "category": "cocktails-mocktails",
    "subcategory": "Signature Mocktails",
    "description": "fresh kiwi with citrus, lively and tropical.",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "cocktails-mocktails-signature-mocktails-passion-fruit-delight",
    "name": "Passion Fruit Delight",
    "category": "cocktails-mocktails",
    "subcategory": "Signature Mocktails",
    "description": "passion fruit and citrus.",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "cocktails-mocktails-signature-mocktails-mango-tango",
    "name": "Mango Tango",
    "category": "cocktails-mocktails",
    "subcategory": "Signature Mocktails",
    "description": "sweet ripe mango with tropical flavours.",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "cocktails-mocktails-signature-mocktails-tropical-sunrise",
    "name": "Tropical Sunrise",
    "category": "cocktails-mocktails",
    "subcategory": "Signature Mocktails",
    "description": "colourful tropical fruits with a sunrise effect.",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "cocktails-mocktails-signature-mocktails-mango-passion-fizz",
    "name": "Mango Passion Fizz",
    "category": "cocktails-mocktails",
    "subcategory": "Signature Mocktails",
    "description": "mango and passion fruit with sparkle.",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "cocktails-mocktails-signature-mocktails-virgin-mary",
    "name": "Virgin Mary",
    "category": "cocktails-mocktails",
    "subcategory": "Signature Mocktails",
    "description": "non-alcoholic tomato drink with citrus, spices and a savoury finish.",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "cocktails-mocktails-signature-mocktails-virgin-strawberry-daiquiri",
    "name": "Virgin Strawberry Daiquiri",
    "category": "cocktails-mocktails",
    "subcategory": "Signature Mocktails",
    "description": "strawberries, lime and sweetness, frozen-style.",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "cocktails-mocktails-haandi-mojito-collection-classic-mojito",
    "name": "Classic Mojito",
    "category": "cocktails-mocktails",
    "subcategory": "Haandi Mojito Collection",
    "description": "white rum, lime, mint, sugar, soda.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": null
  },
  {
    "id": "cocktails-mocktails-haandi-mojito-collection-passion-fruit-mojito",
    "name": "Passion Fruit Mojito",
    "category": "cocktails-mocktails",
    "subcategory": "Haandi Mojito Collection",
    "description": "white rum, passion fruit, lime, mint, soda.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": null
  },
  {
    "id": "cocktails-mocktails-haandi-mojito-collection-strawberry-mojito",
    "name": "Strawberry Mojito",
    "category": "cocktails-mocktails",
    "subcategory": "Haandi Mojito Collection",
    "description": "white rum, strawberries, lime, mint, soda.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": null
  },
  {
    "id": "cocktails-mocktails-haandi-mojito-collection-mango-mojito",
    "name": "Mango Mojito",
    "category": "cocktails-mocktails",
    "subcategory": "Haandi Mojito Collection",
    "description": "white rum, ripe mango, lime, mint, soda.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": null
  },
  {
    "id": "cocktails-mocktails-classic-signature-cocktails-pi-a-colada",
    "name": "Piña Colada",
    "category": "cocktails-mocktails",
    "subcategory": "Classic & Signature Cocktails",
    "description": "white rum, pineapple and coconut.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": null
  },
  {
    "id": "cocktails-mocktails-classic-signature-cocktails-pi-a-colada-whole-pineapple",
    "name": "Piña Colada (Whole Pineapple)",
    "category": "cocktails-mocktails",
    "subcategory": "Classic & Signature Cocktails",
    "description": "our signature, served in a whole fresh pineapple.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "Whole Pineapple"
  },
  {
    "id": "cocktails-mocktails-classic-signature-cocktails-long-island-iced-tea",
    "name": "Long Island Iced Tea",
    "category": "cocktails-mocktails",
    "subcategory": "Classic & Signature Cocktails",
    "description": "vodka, gin, rum, tequila, triple sec, lemon and cola.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": null
  },
  {
    "id": "cocktails-mocktails-classic-signature-cocktails-blue-lagoon",
    "name": "Blue Lagoon",
    "category": "cocktails-mocktails",
    "subcategory": "Classic & Signature Cocktails",
    "description": "vodka, citrus and blue curaçao.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": null
  },
  {
    "id": "cocktails-mocktails-classic-signature-cocktails-whiskey-sour",
    "name": "Whiskey Sour",
    "category": "cocktails-mocktails",
    "subcategory": "Classic & Signature Cocktails",
    "description": "whiskey, fresh lemon and sweetness.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": null
  },
  {
    "id": "cocktails-mocktails-classic-signature-cocktails-bloody-mary",
    "name": "Bloody Mary",
    "category": "cocktails-mocktails",
    "subcategory": "Classic & Signature Cocktails",
    "description": "vodka, tomato juice, lemon and spices.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": null
  },
  {
    "id": "cocktails-mocktails-classic-signature-cocktails-margarita",
    "name": "Margarita",
    "category": "cocktails-mocktails",
    "subcategory": "Classic & Signature Cocktails",
    "description": "tequila, orange liqueur and fresh lime.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": null
  },
  {
    "id": "cocktails-mocktails-classic-signature-cocktails-daiquiri",
    "name": "Daiquiri",
    "category": "cocktails-mocktails",
    "subcategory": "Classic & Signature Cocktails",
    "description": "white rum, fresh lime and sweetness.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": null
  },
  {
    "id": "cocktails-mocktails-classic-signature-cocktails-tequila-sunrise",
    "name": "Tequila Sunrise",
    "category": "cocktails-mocktails",
    "subcategory": "Classic & Signature Cocktails",
    "description": "tequila, orange and grenadine.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": null
  },
  {
    "id": "cocktails-mocktails-classic-signature-cocktails-cosmopolitan",
    "name": "Cosmopolitan",
    "category": "cocktails-mocktails",
    "subcategory": "Classic & Signature Cocktails",
    "description": "vodka, orange liqueur, cranberry and lime.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": null
  },
  {
    "id": "cocktails-mocktails-classic-signature-cocktails-old-fashioned",
    "name": "Old Fashioned",
    "category": "cocktails-mocktails",
    "subcategory": "Classic & Signature Cocktails",
    "description": "whiskey, bitters and sweetness, stirred.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": null
  },
  {
    "id": "cocktails-mocktails-classic-signature-cocktails-moscow-mule",
    "name": "Moscow Mule",
    "category": "cocktails-mocktails",
    "subcategory": "Classic & Signature Cocktails",
    "description": "vodka, ginger beer and lime.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": null
  },
  {
    "id": "cocktails-mocktails-classic-signature-cocktails-gin-tonic",
    "name": "Gin & Tonic",
    "category": "cocktails-mocktails",
    "subcategory": "Classic & Signature Cocktails",
    "description": "premium gin and tonic with fresh garnish.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": null
  },
  {
    "id": "cocktails-mocktails-classic-signature-cocktails-dry-martini",
    "name": "Dry Martini",
    "category": "cocktails-mocktails",
    "subcategory": "Classic & Signature Cocktails",
    "description": "gin and dry vermouth.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": null
  },
  {
    "id": "cocktails-mocktails-classic-signature-cocktails-screwdriver",
    "name": "Screwdriver",
    "category": "cocktails-mocktails",
    "subcategory": "Classic & Signature Cocktails",
    "description": "vodka and fresh orange juice.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": null
  },
  {
    "id": "cocktails-mocktails-classic-signature-cocktails-manhattan",
    "name": "Manhattan",
    "category": "cocktails-mocktails",
    "subcategory": "Classic & Signature Cocktails",
    "description": "whiskey, sweet vermouth and bitters.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": null
  },
  {
    "id": "cocktails-mocktails-classic-signature-cocktails-negroni",
    "name": "Negroni",
    "category": "cocktails-mocktails",
    "subcategory": "Classic & Signature Cocktails",
    "description": "gin, Campari and sweet vermouth.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": null
  },
  {
    "id": "cocktails-mocktails-sharing-cocktails-red-wine-sangria",
    "name": "Red Wine Sangria",
    "category": "cocktails-mocktails",
    "subcategory": "Sharing Cocktails",
    "description": "red wine, fresh fruit and citrus.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": null
  },
  {
    "id": "cocktails-mocktails-sharing-cocktails-white-wine-sangria",
    "name": "White Wine Sangria",
    "category": "cocktails-mocktails",
    "subcategory": "Sharing Cocktails",
    "description": "white wine, fresh fruit and citrus, light and crisp.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": null
  },
  {
    "id": "cocktails-mocktails-sharing-cocktails-tropical-sangria",
    "name": "Tropical Sangria",
    "category": "cocktails-mocktails",
    "subcategory": "Sharing Cocktails",
    "description": "wine with tropical fruits.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": null
  },
  {
    "id": "cocktails-mocktails-sharing-cocktails-pitchers-red-wine-sangria",
    "name": "Pitchers: Red Wine Sangria",
    "category": "cocktails-mocktails",
    "subcategory": "Sharing Cocktails",
    "description": "Please drink responsibly.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": null
  },
  {
    "id": "cocktails-mocktails-sharing-cocktails-white-wine-sangria-2",
    "name": "White Wine Sangria",
    "category": "cocktails-mocktails",
    "subcategory": "Sharing Cocktails",
    "description": "white wine, fresh fruit and citrus, light and crisp.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": null
  },
  {
    "id": "cocktails-mocktails-sharing-cocktails-tropical-sangria-2",
    "name": "Tropical Sangria",
    "category": "cocktails-mocktails",
    "subcategory": "Sharing Cocktails",
    "description": "wine with tropical fruits.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": null
  },
  {
    "id": "cocktails-mocktails-sharing-cocktails-classic-mojito",
    "name": "Classic Mojito",
    "category": "cocktails-mocktails",
    "subcategory": "Sharing Cocktails",
    "description": "white rum, lime, mint, sugar, soda.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": null
  },
  {
    "id": "cocktails-mocktails-sharing-cocktails-passion-fruit-mojito",
    "name": "Passion Fruit Mojito",
    "category": "cocktails-mocktails",
    "subcategory": "Sharing Cocktails",
    "description": "white rum, passion fruit, lime, mint, soda.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": null
  },
  {
    "id": "cocktails-mocktails-sharing-cocktails-long-island-iced-tea",
    "name": "Long Island Iced Tea",
    "category": "cocktails-mocktails",
    "subcategory": "Sharing Cocktails",
    "description": "vodka, gin, rum, tequila, triple sec, lemon and cola.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": null
  },
  {
    "id": "cocktails-mocktails-sharing-cocktails-fruit-punch",
    "name": "Fruit Punch",
    "category": "cocktails-mocktails",
    "subcategory": "Sharing Cocktails",
    "description": "tropical fruit juices, sweet and tangy.",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "cocktails-mocktails-sharing-cocktails-pitcher-red-wine-sangria",
    "name": "Pitcher Red Wine Sangria",
    "category": "cocktails-mocktails",
    "subcategory": "Sharing Cocktails",
    "description": "Please drink responsibly.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "Pitcher"
  },
  {
    "id": "cocktails-mocktails-sharing-cocktails-pitcher-white-wine-sangria",
    "name": "Pitcher White Wine Sangria",
    "category": "cocktails-mocktails",
    "subcategory": "Sharing Cocktails",
    "description": "Please drink responsibly.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "Pitcher"
  },
  {
    "id": "cocktails-mocktails-sharing-cocktails-pitcher-tropical-sangria",
    "name": "Pitcher Tropical Sangria",
    "category": "cocktails-mocktails",
    "subcategory": "Sharing Cocktails",
    "description": "Please drink responsibly.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "Pitcher"
  },
  {
    "id": "cocktails-mocktails-sharing-cocktails-pitcher-classic-mojito",
    "name": "Pitcher Classic Mojito",
    "category": "cocktails-mocktails",
    "subcategory": "Sharing Cocktails",
    "description": "Please drink responsibly.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "Pitcher"
  },
  {
    "id": "cocktails-mocktails-sharing-cocktails-pitcher-passion-fruit-mojito",
    "name": "Pitcher Passion Fruit Mojito",
    "category": "cocktails-mocktails",
    "subcategory": "Sharing Cocktails",
    "description": "Please drink responsibly.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "Pitcher"
  },
  {
    "id": "cocktails-mocktails-sharing-cocktails-pitcher-long-island-iced-tea",
    "name": "Pitcher Long Island Iced Tea",
    "category": "cocktails-mocktails",
    "subcategory": "Sharing Cocktails",
    "description": "Please drink responsibly.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "Pitcher"
  },
  {
    "id": "cocktails-mocktails-sharing-cocktails-pitcher-fruit-punch",
    "name": "Pitcher Fruit Punch",
    "category": "cocktails-mocktails",
    "subcategory": "Sharing Cocktails",
    "description": "Please drink responsibly.",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": "Pitcher"
  },
  {
    "id": "cocktails-mocktails-shooters-j-ger-bomb",
    "name": "Jäger Bomb",
    "category": "cocktails-mocktails",
    "subcategory": "Shooters",
    "description": "Jägermeister with an energy drink.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": null
  },
  {
    "id": "cocktails-mocktails-shooters-b-52",
    "name": "B-52",
    "category": "cocktails-mocktails",
    "subcategory": "Shooters",
    "description": "coffee liqueur, Irish cream and orange liqueur, layered.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": null
  },
  {
    "id": "cocktails-mocktails-shooters-kamikaze",
    "name": "Kamikaze",
    "category": "cocktails-mocktails",
    "subcategory": "Shooters",
    "description": "vodka, orange liqueur and fresh lime.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": null
  },
  {
    "id": "cocktails-mocktails-shooters-tequila-shot",
    "name": "Tequila Shot",
    "category": "cocktails-mocktails",
    "subcategory": "Shooters",
    "description": "served chilled with salt and lime.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": null
  },
  {
    "id": "cocktails-mocktails-shooters-sambuca-shot",
    "name": "Sambuca Shot",
    "category": "cocktails-mocktails",
    "subcategory": "Shooters",
    "description": "aromatic anise liqueur.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": null
  },
  {
    "id": "beer-chilled-beers-local-bell-lager",
    "name": "Bell Lager",
    "category": "beer",
    "subcategory": "Chilled Beers — Local",
    "description": "",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": null
  },
  {
    "id": "beer-chilled-beers-local-guinness-stout",
    "name": "Guinness Stout",
    "category": "beer",
    "subcategory": "Chilled Beers — Local",
    "description": "",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": null
  },
  {
    "id": "beer-chilled-beers-local-guinness-smooth",
    "name": "Guinness Smooth",
    "category": "beer",
    "subcategory": "Chilled Beers — Local",
    "description": "",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": null
  },
  {
    "id": "beer-chilled-beers-local-tusker-lager",
    "name": "Tusker Lager",
    "category": "beer",
    "subcategory": "Chilled Beers — Local",
    "description": "",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": null
  },
  {
    "id": "beer-chilled-beers-local-tusker-malt",
    "name": "Tusker Malt",
    "category": "beer",
    "subcategory": "Chilled Beers — Local",
    "description": "",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": null
  },
  {
    "id": "beer-chilled-beers-local-tusker-lite",
    "name": "Tusker Lite",
    "category": "beer",
    "subcategory": "Chilled Beers — Local",
    "description": "",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": null
  },
  {
    "id": "beer-chilled-beers-local-tusker-cider",
    "name": "Tusker Cider",
    "category": "beer",
    "subcategory": "Chilled Beers — Local",
    "description": "",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": null
  },
  {
    "id": "beer-chilled-beers-local-smirnoff-ice-black",
    "name": "Smirnoff Ice Black",
    "category": "beer",
    "subcategory": "Chilled Beers — Local",
    "description": "",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": null
  },
  {
    "id": "beer-chilled-beers-local-castle-lite",
    "name": "Castle Lite",
    "category": "beer",
    "subcategory": "Chilled Beers — Local",
    "description": "",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": null
  },
  {
    "id": "beer-chilled-beers-local-club",
    "name": "Club",
    "category": "beer",
    "subcategory": "Chilled Beers — Local",
    "description": "",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": null
  },
  {
    "id": "beer-chilled-beers-imported-heineken",
    "name": "Heineken",
    "category": "beer",
    "subcategory": "Chilled Beers — Imported",
    "description": "",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": null
  },
  {
    "id": "beer-chilled-beers-imported-corona",
    "name": "Corona",
    "category": "beer",
    "subcategory": "Chilled Beers — Imported",
    "description": "",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": null
  },
  {
    "id": "beer-chilled-beers-imported-cavana-cider",
    "name": "Cavana Cider",
    "category": "beer",
    "subcategory": "Chilled Beers — Imported",
    "description": "",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": null
  },
  {
    "id": "beer-chilled-beers-imported-non-alcoholic-beer",
    "name": "Non-Alcoholic Beer",
    "category": "beer",
    "subcategory": "Chilled Beers — Imported",
    "description": "",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "wine-red-wine-kwv-pinotage",
    "name": "KWV Pinotage",
    "category": "wine",
    "subcategory": "Red Wine",
    "description": "ripe berry, gentle spice, smooth finish.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "By the glass and bottle where applicable"
  },
  {
    "id": "wine-red-wine-kwv-merlot",
    "name": "KWV Merlot",
    "category": "wine",
    "subcategory": "Red Wine",
    "description": "soft, ripe red fruit, easy-drinking.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "By the glass and bottle where applicable"
  },
  {
    "id": "wine-red-wine-kwv-shiraz",
    "name": "KWV Shiraz",
    "category": "wine",
    "subcategory": "Red Wine",
    "description": "dark berries, subtle spice, warm finish.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "By the glass and bottle where applicable"
  },
  {
    "id": "wine-red-wine-nederburg-cabernet-sauvignon",
    "name": "Nederburg Cabernet Sauvignon",
    "category": "wine",
    "subcategory": "Red Wine",
    "description": "full-bodied, dark fruit, subtle oak.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "By the glass and bottle where applicable"
  },
  {
    "id": "wine-red-wine-nederburg-shiraz",
    "name": "Nederburg Shiraz",
    "category": "wine",
    "subcategory": "Red Wine",
    "description": "bold, ripe berries and spice.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "By the glass and bottle where applicable"
  },
  {
    "id": "wine-red-wine-calvet-cabernet-sauvignon",
    "name": "Calvet Cabernet Sauvignon",
    "category": "wine",
    "subcategory": "Red Wine",
    "description": "Bordeaux-style, black fruit, balanced tannins.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "By the glass and bottle where applicable"
  },
  {
    "id": "wine-red-wine-calvet-reserve-bordeaux-merlot-cabernet-sauvignon",
    "name": "Calvet Reserve Bordeaux Merlot Cabernet Sauvignon",
    "category": "wine",
    "subcategory": "Red Wine",
    "description": "refined blend, ripe fruit, balanced oak.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "By the glass and bottle where applicable"
  },
  {
    "id": "wine-red-wine-four-cousins-red-sweet-750-ml",
    "name": "Four Cousins Red Sweet (750 ml)",
    "category": "wine",
    "subcategory": "Red Wine",
    "description": "fruity, sweet, approachable.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "By the glass and bottle where applicable"
  },
  {
    "id": "wine-red-wine-four-cousins-red-dry-1-5-l",
    "name": "Four Cousins Red Dry (1.5 L)",
    "category": "wine",
    "subcategory": "Red Wine",
    "description": "smooth dry red, ideal for sharing.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "By the glass and bottle where applicable"
  },
  {
    "id": "wine-red-wine-jacob-s-creek-classic-shiraz",
    "name": "Jacob’s Creek Classic Shiraz",
    "category": "wine",
    "subcategory": "Red Wine",
    "description": "Australian, ripe berry, subtle spice.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "By the glass and bottle where applicable"
  },
  {
    "id": "wine-red-wine-kanonkop-kadette-cabernet-sauvignon",
    "name": "Kanonkop Kadette Cabernet Sauvignon",
    "category": "wine",
    "subcategory": "Red Wine",
    "description": "premium South African, dark fruit, elegant structure.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "By the glass and bottle where applicable"
  },
  {
    "id": "wine-red-wine-masi-campofiorin",
    "name": "Masi Campofiorin",
    "category": "wine",
    "subcategory": "Red Wine",
    "description": "Italian, ripe cherry, spice, rounded finish.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "By the glass and bottle where applicable"
  },
  {
    "id": "wine-red-wine-masi-costasera-amarone",
    "name": "Masi Costasera Amarone",
    "category": "wine",
    "subcategory": "Red Wine",
    "description": "luxurious Amarone, concentrated dark fruit, long velvety finish.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "By the glass and bottle where applicable"
  },
  {
    "id": "wine-white-wine-kwv-chardonnay",
    "name": "KWV Chardonnay",
    "category": "wine",
    "subcategory": "White Wine",
    "description": "smooth, fresh, ripe fruit.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "By the glass and bottle where applicable"
  },
  {
    "id": "wine-white-wine-kwv-chenin-blanc",
    "name": "KWV Chenin Blanc",
    "category": "wine",
    "subcategory": "White Wine",
    "description": "lively, bright fruit, clean finish.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "By the glass and bottle where applicable"
  },
  {
    "id": "wine-white-wine-kwv-sauvignon-blanc",
    "name": "KWV Sauvignon Blanc",
    "category": "wine",
    "subcategory": "White Wine",
    "description": "crisp, citrus and tropical fruit.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "By the glass and bottle where applicable"
  },
  {
    "id": "wine-white-wine-calvet-chardonnay",
    "name": "Calvet Chardonnay",
    "category": "wine",
    "subcategory": "White Wine",
    "description": "elegant, fresh fruit, soft finish.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "By the glass and bottle where applicable"
  },
  {
    "id": "wine-white-wine-calvet-reserve-bordeaux-sauvignon-blanc",
    "name": "Calvet Reserve Bordeaux Sauvignon Blanc",
    "category": "wine",
    "subcategory": "White Wine",
    "description": "citrus, herbal and tropical notes.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "By the glass and bottle where applicable"
  },
  {
    "id": "wine-white-wine-four-cousins-white-sweet-1-5-l",
    "name": "Four Cousins White Sweet (1.5 L)",
    "category": "wine",
    "subcategory": "White Wine",
    "description": "fruity, fresh, gently sweet.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "By the glass and bottle where applicable"
  },
  {
    "id": "wine-white-wine-four-cousins-white-dry-1-5-l",
    "name": "Four Cousins White Dry (1.5 L)",
    "category": "wine",
    "subcategory": "White Wine",
    "description": "crisp, clean fruit, ideal for sharing.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "By the glass and bottle where applicable"
  },
  {
    "id": "wine-white-wine-masi-masianco-pinot-grigio",
    "name": "Masi Masianco Pinot Grigio",
    "category": "wine",
    "subcategory": "White Wine",
    "description": "Italian, citrus, pear and tropical fruit.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "By the glass and bottle where applicable"
  },
  {
    "id": "wine-ros-wine-kwv-classic-shiraz-ros",
    "name": "KWV Classic Shiraz Rosé",
    "category": "wine",
    "subcategory": "Rosé Wine",
    "description": "fresh, bright berry, crisp finish.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "By the glass and bottle where applicable"
  },
  {
    "id": "wine-ros-wine-ken-forrester-petit-ros",
    "name": "Ken Forrester Petit Rosé",
    "category": "wine",
    "subcategory": "Rosé Wine",
    "description": "elegant, delicate fruit, clean finish.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "By the glass and bottle where applicable"
  },
  {
    "id": "wine-sparkling-wine-kwv-sparkling-cuv-e-brut",
    "name": "KWV Sparkling Cuvée Brut",
    "category": "wine",
    "subcategory": "Sparkling Wine",
    "description": "crisp, delicate bubbles, dry finish.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "By the glass and bottle where applicable"
  },
  {
    "id": "wine-sparkling-wine-calvet-celebration-brut-sparkling",
    "name": "Calvet Celebration Brut Sparkling",
    "category": "wine",
    "subcategory": "Sparkling Wine",
    "description": "bright, fine bubbles, celebratory.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "By the glass and bottle where applicable"
  },
  {
    "id": "wine-sparkling-wine-signore-giuseppe-prosecco-extra-dry",
    "name": "Signore Giuseppe Prosecco Extra Dry",
    "category": "wine",
    "subcategory": "Sparkling Wine",
    "description": "Italian, fine bubbles, lightly sweet.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "By the glass and bottle where applicable"
  },
  {
    "id": "wine-champagne-mo-t-chandon-brut-imp-rial",
    "name": "Moët & Chandon Brut Impérial",
    "category": "wine",
    "subcategory": "Champagne",
    "description": "iconic French Champagne, elegant and refined.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "By the glass and bottle where applicable"
  },
  {
    "id": "wine-champagne-mo-t-chandon-ros",
    "name": "Moët & Chandon Rosé",
    "category": "wine",
    "subcategory": "Champagne",
    "description": "red-fruit character, delicate bubbles.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "By the glass and bottle where applicable"
  },
  {
    "id": "wine-champagne-mumm-cordon-rouge-brut",
    "name": "Mumm Cordon Rouge Brut",
    "category": "wine",
    "subcategory": "Champagne",
    "description": "fresh fruit, citrus, crisp finish.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "By the glass and bottle where applicable"
  },
  {
    "id": "spirits-per-tot-30-ml-johnnie-walker-red-label",
    "name": "Johnnie Walker Red Label",
    "category": "spirits",
    "subcategory": "Per tot · 30 ml",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-per-tot-30-ml-johnnie-walker-black-label",
    "name": "Johnnie Walker Black Label",
    "category": "spirits",
    "subcategory": "Per tot · 30 ml",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-per-tot-30-ml-johnnie-walker-green-label-15-yrs",
    "name": "Johnnie Walker Green Label 15 Yrs",
    "category": "spirits",
    "subcategory": "Per tot · 30 ml",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-per-tot-30-ml-johnnie-walker-gold-label-reserve",
    "name": "Johnnie Walker Gold Label Reserve",
    "category": "spirits",
    "subcategory": "Per tot · 30 ml",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-per-tot-30-ml-chivas-regal-12-yrs",
    "name": "Chivas Regal 12 Yrs",
    "category": "spirits",
    "subcategory": "Per tot · 30 ml",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-per-tot-30-ml-chivas-regal-18-yrs",
    "name": "Chivas Regal 18 Yrs",
    "category": "spirits",
    "subcategory": "Per tot · 30 ml",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-per-tot-30-ml-ballantine-s",
    "name": "Ballantine’s",
    "category": "spirits",
    "subcategory": "Per tot · 30 ml",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-per-tot-30-ml-j-b-rare",
    "name": "J&B Rare",
    "category": "spirits",
    "subcategory": "Per tot · 30 ml",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-per-tot-30-ml-teacher-s-highland-cream",
    "name": "Teacher’s Highland Cream",
    "category": "spirits",
    "subcategory": "Per tot · 30 ml",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-per-tot-30-ml-vat-69",
    "name": "VAT 69",
    "category": "spirits",
    "subcategory": "Per tot · 30 ml",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-per-tot-30-ml-all-seasons",
    "name": "All Seasons",
    "category": "spirits",
    "subcategory": "Per tot · 30 ml",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-per-tot-30-ml-the-famous-grouse",
    "name": "The Famous Grouse",
    "category": "spirits",
    "subcategory": "Per tot · 30 ml",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-per-tot-30-ml-jameson",
    "name": "Jameson",
    "category": "spirits",
    "subcategory": "Per tot · 30 ml",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-per-tot-30-ml-jameson-black-barrel",
    "name": "Jameson Black Barrel",
    "category": "spirits",
    "subcategory": "Per tot · 30 ml",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-per-tot-30-ml-jim-beam",
    "name": "Jim Beam",
    "category": "spirits",
    "subcategory": "Per tot · 30 ml",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-per-tot-30-ml-gentleman-jack",
    "name": "Gentleman Jack",
    "category": "spirits",
    "subcategory": "Per tot · 30 ml",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-per-tot-30-ml-jack-daniel-s",
    "name": "Jack Daniel’s",
    "category": "spirits",
    "subcategory": "Per tot · 30 ml",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-per-tot-30-ml-monkey-shoulder",
    "name": "Monkey Shoulder",
    "category": "spirits",
    "subcategory": "Per tot · 30 ml",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-single-malt-glenfiddich-12-yrs",
    "name": "Glenfiddich 12 Yrs",
    "category": "spirits",
    "subcategory": "Single Malt",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-single-malt-glenfiddich-15-yrs",
    "name": "Glenfiddich 15 Yrs",
    "category": "spirits",
    "subcategory": "Single Malt",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-single-malt-glenfiddich-18-yrs",
    "name": "Glenfiddich 18 Yrs",
    "category": "spirits",
    "subcategory": "Single Malt",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-single-malt-the-glenlivet-12-yrs",
    "name": "The Glenlivet 12 Yrs",
    "category": "spirits",
    "subcategory": "Single Malt",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-single-malt-the-glenlivet-15-yrs",
    "name": "The Glenlivet 15 Yrs",
    "category": "spirits",
    "subcategory": "Single Malt",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-single-malt-the-glenlivet-18-yrs",
    "name": "The Glenlivet 18 Yrs",
    "category": "spirits",
    "subcategory": "Single Malt",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-single-malt-singleton-12-yrs",
    "name": "Singleton 12 Yrs",
    "category": "spirits",
    "subcategory": "Single Malt",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-single-malt-singleton-15-yrs",
    "name": "Singleton 15 Yrs",
    "category": "spirits",
    "subcategory": "Single Malt",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-single-malt-singleton-18-yrs",
    "name": "Singleton 18 Yrs",
    "category": "spirits",
    "subcategory": "Single Malt",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-single-malt-aberlour-12-yrs",
    "name": "Aberlour 12 Yrs",
    "category": "spirits",
    "subcategory": "Single Malt",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-single-malt-lagavulin-16-yrs",
    "name": "Lagavulin 16 Yrs",
    "category": "spirits",
    "subcategory": "Single Malt",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-single-malt-the-macallan-12-yrs",
    "name": "The Macallan 12 Yrs",
    "category": "spirits",
    "subcategory": "Single Malt",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-single-malt-talisker-10-yrs",
    "name": "Talisker 10 Yrs",
    "category": "spirits",
    "subcategory": "Single Malt",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-single-malt-glenmorangie-original-10-yrs",
    "name": "Glenmorangie Original 10 Yrs",
    "category": "spirits",
    "subcategory": "Single Malt",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-bourbon-american-whiskey-jim-beam",
    "name": "Jim Beam",
    "category": "spirits",
    "subcategory": "Bourbon & American Whiskey",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-bourbon-american-whiskey-jack-daniel-s",
    "name": "Jack Daniel’s",
    "category": "spirits",
    "subcategory": "Bourbon & American Whiskey",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-bourbon-american-whiskey-gentleman-jack",
    "name": "Gentleman Jack",
    "category": "spirits",
    "subcategory": "Bourbon & American Whiskey",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-bourbon-american-whiskey-maker-s-mark",
    "name": "Maker’s Mark",
    "category": "spirits",
    "subcategory": "Bourbon & American Whiskey",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-bourbon-american-whiskey-woodford-reserve",
    "name": "Woodford Reserve",
    "category": "spirits",
    "subcategory": "Bourbon & American Whiskey",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-rum-bacardi-white",
    "name": "Bacardi White",
    "category": "spirits",
    "subcategory": "Rum",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-rum-bacardi-black",
    "name": "Bacardi Black",
    "category": "spirits",
    "subcategory": "Rum",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-rum-bacardi-gold",
    "name": "Bacardi Gold",
    "category": "spirits",
    "subcategory": "Rum",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-rum-malibu",
    "name": "Malibu",
    "category": "spirits",
    "subcategory": "Rum",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-rum-captain-morgan-spiced-gold",
    "name": "Captain Morgan Spiced Gold",
    "category": "spirits",
    "subcategory": "Rum",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-rum-captain-morgan-dark",
    "name": "Captain Morgan Dark",
    "category": "spirits",
    "subcategory": "Rum",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-rum-havana-club-3-yrs",
    "name": "Havana Club 3 Yrs",
    "category": "spirits",
    "subcategory": "Rum",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-rum-havana-club-7-yrs",
    "name": "Havana Club 7 Yrs",
    "category": "spirits",
    "subcategory": "Rum",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-vodka-opm",
    "name": "OPM",
    "category": "spirits",
    "subcategory": "Vodka",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-vodka-smirnoff",
    "name": "Smirnoff",
    "category": "spirits",
    "subcategory": "Vodka",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-vodka-absolut",
    "name": "Absolut",
    "category": "spirits",
    "subcategory": "Vodka",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-vodka-absolut-vanilla",
    "name": "Absolut Vanilla",
    "category": "spirits",
    "subcategory": "Vodka",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-vodka-c-roc",
    "name": "Cîroc",
    "category": "spirits",
    "subcategory": "Vodka",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-vodka-grey-goose",
    "name": "Grey Goose",
    "category": "spirits",
    "subcategory": "Vodka",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-vodka-belvedere",
    "name": "Belvedere",
    "category": "spirits",
    "subcategory": "Vodka",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-gin-ug-premium",
    "name": "UG Premium",
    "category": "spirits",
    "subcategory": "Gin",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-gin-ug-coconut",
    "name": "UG Coconut",
    "category": "spirits",
    "subcategory": "Gin",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-gin-ug-ginger-lemon",
    "name": "UG Ginger Lemon",
    "category": "spirits",
    "subcategory": "Gin",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-gin-gilbey-s",
    "name": "Gilbey’s",
    "category": "spirits",
    "subcategory": "Gin",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-gin-gordon-s",
    "name": "Gordon’s",
    "category": "spirits",
    "subcategory": "Gin",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-gin-bombay-sapphire",
    "name": "Bombay Sapphire",
    "category": "spirits",
    "subcategory": "Gin",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-gin-beefeater-dry",
    "name": "Beefeater Dry",
    "category": "spirits",
    "subcategory": "Gin",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-gin-tanqueray-london-dry",
    "name": "Tanqueray London Dry",
    "category": "spirits",
    "subcategory": "Gin",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-gin-hendrick-s",
    "name": "Hendrick’s",
    "category": "spirits",
    "subcategory": "Gin",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-tequila-gold-tequila",
    "name": "Gold Tequila",
    "category": "spirits",
    "subcategory": "Tequila",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-tequila-silver-tequila",
    "name": "Silver Tequila",
    "category": "spirits",
    "subcategory": "Tequila",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-tequila-chocolate-tequila",
    "name": "Chocolate Tequila",
    "category": "spirits",
    "subcategory": "Tequila",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-tequila-jose-cuervo-silver",
    "name": "Jose Cuervo Silver",
    "category": "spirits",
    "subcategory": "Tequila",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-tequila-jose-cuervo-gold",
    "name": "Jose Cuervo Gold",
    "category": "spirits",
    "subcategory": "Tequila",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-tequila-olmeca-blanco",
    "name": "Olmeca Blanco",
    "category": "spirits",
    "subcategory": "Tequila",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-tequila-olmeca-gold",
    "name": "Olmeca Gold",
    "category": "spirits",
    "subcategory": "Tequila",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-brandy-cognac-kwv-5-yrs",
    "name": "KWV 5 Yrs",
    "category": "spirits",
    "subcategory": "Brandy & Cognac",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-brandy-cognac-kwv-10-yrs",
    "name": "KWV 10 Yrs",
    "category": "spirits",
    "subcategory": "Brandy & Cognac",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-brandy-cognac-viceroy",
    "name": "Viceroy",
    "category": "spirits",
    "subcategory": "Brandy & Cognac",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-brandy-cognac-martell-vs",
    "name": "Martell VS",
    "category": "spirits",
    "subcategory": "Brandy & Cognac",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-brandy-cognac-martell-vsop",
    "name": "Martell VSOP",
    "category": "spirits",
    "subcategory": "Brandy & Cognac",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-brandy-cognac-r-my-martin-vsop",
    "name": "Rémy Martin VSOP",
    "category": "spirits",
    "subcategory": "Brandy & Cognac",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-brandy-cognac-r-my-martin-xo",
    "name": "Rémy Martin XO",
    "category": "spirits",
    "subcategory": "Brandy & Cognac",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-brandy-cognac-hennessy-vs",
    "name": "Hennessy VS",
    "category": "spirits",
    "subcategory": "Brandy & Cognac",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-brandy-cognac-hennessy-vsop",
    "name": "Hennessy VSOP",
    "category": "spirits",
    "subcategory": "Brandy & Cognac",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-liqueurs-amarula-cream",
    "name": "Amarula Cream",
    "category": "spirits",
    "subcategory": "Liqueurs",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-liqueurs-baileys-irish-cream",
    "name": "Baileys Irish Cream",
    "category": "spirits",
    "subcategory": "Liqueurs",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-liqueurs-cointreau",
    "name": "Cointreau",
    "category": "spirits",
    "subcategory": "Liqueurs",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-liqueurs-j-germeister",
    "name": "Jägermeister",
    "category": "spirits",
    "subcategory": "Liqueurs",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-liqueurs-green-zappa",
    "name": "Green Zappa",
    "category": "spirits",
    "subcategory": "Liqueurs",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-liqueurs-campari-bitter",
    "name": "Campari Bitter",
    "category": "spirits",
    "subcategory": "Liqueurs",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-liqueurs-kahl-a",
    "name": "Kahlúa",
    "category": "spirits",
    "subcategory": "Liqueurs",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-liqueurs-southern-comfort",
    "name": "Southern Comfort",
    "category": "spirits",
    "subcategory": "Liqueurs",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-liqueurs-tia-maria",
    "name": "Tia Maria",
    "category": "spirits",
    "subcategory": "Liqueurs",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-liqueurs-triple-sec",
    "name": "Triple Sec",
    "category": "spirits",
    "subcategory": "Liqueurs",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-liqueurs-sambuca",
    "name": "Sambuca",
    "category": "spirits",
    "subcategory": "Liqueurs",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-liqueurs-disaronno-amaretto",
    "name": "Disaronno Amaretto",
    "category": "spirits",
    "subcategory": "Liqueurs",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-liqueurs-blue-cura-ao",
    "name": "Blue Curaçao",
    "category": "spirits",
    "subcategory": "Liqueurs",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-liqueurs-martini-bianco",
    "name": "Martini Bianco",
    "category": "spirits",
    "subcategory": "Liqueurs",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-liqueurs-martini-rosso",
    "name": "Martini Rosso",
    "category": "spirits",
    "subcategory": "Liqueurs",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-liqueurs-martini-extra-dry",
    "name": "Martini Extra Dry",
    "category": "spirits",
    "subcategory": "Liqueurs",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-liqueurs-aperol",
    "name": "Aperol",
    "category": "spirits",
    "subcategory": "Liqueurs",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-vermouth-aperitifs-martini-bianco",
    "name": "Martini Bianco",
    "category": "spirits",
    "subcategory": "Vermouth & Aperitifs",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-vermouth-aperitifs-martini-rosso",
    "name": "Martini Rosso",
    "category": "spirits",
    "subcategory": "Vermouth & Aperitifs",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-vermouth-aperitifs-martini-extra-dry",
    "name": "Martini Extra Dry",
    "category": "spirits",
    "subcategory": "Vermouth & Aperitifs",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-vermouth-aperitifs-aperol",
    "name": "Aperol",
    "category": "spirits",
    "subcategory": "Vermouth & Aperitifs",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "spirits-vermouth-aperitifs-campari",
    "name": "Campari",
    "category": "spirits",
    "subcategory": "Vermouth & Aperitifs",
    "description": "Spirits are served as 30 ml per tot.",
    "price": null,
    "image": "",
    "alcoholic": true,
    "serving": "30 ml per tot"
  },
  {
    "id": "mixers-mixers-tonic-water",
    "name": "Tonic Water",
    "category": "mixers",
    "subcategory": "Mixers",
    "description": "",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "mixers-mixers-soda-water",
    "name": "Soda Water",
    "category": "mixers",
    "subcategory": "Mixers",
    "description": "",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "mixers-mixers-ginger-ale",
    "name": "Ginger Ale",
    "category": "mixers",
    "subcategory": "Mixers",
    "description": "",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "mixers-mixers-cola",
    "name": "Cola",
    "category": "mixers",
    "subcategory": "Mixers",
    "description": "",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "mixers-mixers-lemon-lime-soda",
    "name": "Lemon-Lime Soda",
    "category": "mixers",
    "subcategory": "Mixers",
    "description": "",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "mixers-mixers-ginger-beer",
    "name": "Ginger Beer",
    "category": "mixers",
    "subcategory": "Mixers",
    "description": "",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "mixers-fresh-mixers-fresh-lime",
    "name": "Fresh Lime",
    "category": "mixers",
    "subcategory": "Fresh Mixers",
    "description": "",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "mixers-fresh-mixers-fresh-lemon",
    "name": "Fresh Lemon",
    "category": "mixers",
    "subcategory": "Fresh Mixers",
    "description": "",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "mixers-fresh-mixers-orange-juice",
    "name": "Orange Juice",
    "category": "mixers",
    "subcategory": "Fresh Mixers",
    "description": "",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "mixers-fresh-mixers-pineapple-juice",
    "name": "Pineapple Juice",
    "category": "mixers",
    "subcategory": "Fresh Mixers",
    "description": "",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "mixers-fresh-mixers-passion-fruit-juice",
    "name": "Passion Fruit Juice",
    "category": "mixers",
    "subcategory": "Fresh Mixers",
    "description": "",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "mixers-garnishes-fresh-mint",
    "name": "Fresh Mint",
    "category": "mixers",
    "subcategory": "Garnishes",
    "description": "",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "mixers-garnishes-basil",
    "name": "Basil",
    "category": "mixers",
    "subcategory": "Garnishes",
    "description": "",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "mixers-garnishes-ginger",
    "name": "Ginger",
    "category": "mixers",
    "subcategory": "Garnishes",
    "description": "",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "mixers-garnishes-lemon",
    "name": "Lemon",
    "category": "mixers",
    "subcategory": "Garnishes",
    "description": "",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "mixers-garnishes-lime",
    "name": "Lime",
    "category": "mixers",
    "subcategory": "Garnishes",
    "description": "",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  },
  {
    "id": "mixers-garnishes-seasonal-fruit",
    "name": "Seasonal Fruit",
    "category": "mixers",
    "subcategory": "Garnishes",
    "description": "",
    "price": null,
    "image": "",
    "alcoholic": false,
    "serving": null
  }
];
const ITEM_IMAGE_ASSETS = {
  'butter-chicken': {sourcePage:'https://unsplash.com/photos/brown-and-green-dish-on-brown-wooden-bowl-sqcH2q7lkvo',photographer:'Raman',provider:'Unsplash',license:'Unsplash License',attribution:'No attribution required; attribution appreciated.'},
  'chicken-tikka-masala': {sourcePage:'https://unsplash.com/photos/chicken-tikka-masala-served-with-naan-bread-PXMh2o3tO1s',photographer:'Jessie Maxwell',provider:'Unsplash',license:'Unsplash License',attribution:'No attribution required; attribution appreciated.'},
  'chicken-manchurian': {sourcePage:'https://unsplash.com/photos/a-white-plate-topped-with-meat-and-vegetables-BUPlkEeDmMk',photographer:'Alex Bayev',provider:'Unsplash',license:'Unsplash License',attribution:'No attribution required; attribution appreciated.'},
  'cocktails-mocktails-classic-signature-cocktails-pi-a-colada': {src:'images/items/drinks/pina-colada.webp',sourcePage:'https://unsplash.com/photos/clear-drinking-glass-with-yellow-liquid-and-purple-and-yellow-flower-lD1Yqc0b3kc',photographer:'Daniel Lloyd Blunk-Fernández',provider:'Unsplash',license:'Unsplash License',attribution:'No attribution required; attribution appreciated.'},
  'cocktails-mocktails-haandi-mojito-collection-classic-mojito': {src:'images/items/drinks/classic-mojito-cocktail.webp',sourcePage:'https://unsplash.com/photos/refreshing-mojito-cocktail-with-lemon-and-mint-AquVFyceuXk',photographer:'Mr. Pugo',provider:'Unsplash',license:'Unsplash License',attribution:'No attribution required; attribution appreciated.'}
};
const MENU_ITEMS = [...FOOD,...DRINKS];
MENU_ITEMS.forEach(x=>{const drink=DRINK_GROUPS.some(g=>g.id===x.category);x.image=`images/items/${drink?'drinks':'food'}/${x.id}.webp`});
const ITEM_IMAGE_MANIFEST = MENU_ITEMS.map(x=>{const drink=DRINK_GROUPS.some(g=>g.id===x.category),groups=drink?DRINK_GROUPS:FOOD_CATEGORIES,cat=groups.find(g=>(Array.isArray(g)?g[0]:g.id)===x.category);return{id:x.id,name:x.name,description:x.description||'',kind:drink?'drink':'food',category:x.category,categoryName:Array.isArray(cat)?cat[1]:cat?.name||x.category,subcategory:x.subcategory||null,servingVariant:x.serving??x.variant??null,expectedImagePath:x.image}});
const SIGNATURES = [['Refreshing','Classic Virgin Mojito'],['Indian Favourite','Mango Lassi'],['Fruit Lover','Tropical Fruit Smoothie'],['Milkshake Favourite','Lotus Biscoff Milkshake'],['Cocktail Favourite','Classic Mojito'],['Premium Cocktail','Old Fashioned'],['Red Wine','Calvet Reserve Bordeaux Merlot Cabernet Sauvignon'],['White Wine','KWV Sauvignon Blanc'],['Sparkling','KWV Sparkling Cuvée Brut'],['Champagne','Moët & Chandon Brut Impérial']];
